// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: hestia/jobfair/checkin/v1/checkin.proto

package checkin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	identity "hestia/jobfair/api/pb/identity"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckinRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_EventId     *string                `protobuf:"bytes,2,opt,name=event_id,json=eventId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckinRequest) Reset() {
	*x = CheckinRequest{}
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinRequest) ProtoMessage() {}

func (x *CheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckinRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *CheckinRequest) GetEventId() string {
	if x != nil {
		if x.xxx_hidden_EventId != nil {
			return *x.xxx_hidden_EventId
		}
		return ""
	}
	return ""
}

func (x *CheckinRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CheckinRequest) SetEventId(v string) {
	x.xxx_hidden_EventId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CheckinRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CheckinRequest) HasEventId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CheckinRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *CheckinRequest) ClearEventId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EventId = nil
}

type CheckinRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// token from the QR code
	Token *string
	// if event_id is not empty, the check-in will be associated with the event
	EventId *string
}

func (b0 CheckinRequest_builder) Build() *CheckinRequest {
	m0 := &CheckinRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.EventId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EventId = b.EventId
	}
	return m0
}

type CheckinResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *identity.User         `protobuf:"bytes,1,opt,name=user"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckinResponse) Reset() {
	*x = CheckinResponse{}
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinResponse) ProtoMessage() {}

func (x *CheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckinResponse) GetUser() *identity.User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *CheckinResponse) SetUser(v *identity.User) {
	x.xxx_hidden_User = v
}

func (x *CheckinResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *CheckinResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type CheckinResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *identity.User
}

func (b0 CheckinResponse_builder) Build() *CheckinResponse {
	m0 := &CheckinResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

type CheckinWithCompanyRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_CompanyId   *string                `protobuf:"bytes,2,opt,name=company_id,json=companyId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckinWithCompanyRequest) Reset() {
	*x = CheckinWithCompanyRequest{}
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinWithCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinWithCompanyRequest) ProtoMessage() {}

func (x *CheckinWithCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckinWithCompanyRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *CheckinWithCompanyRequest) GetCompanyId() string {
	if x != nil {
		if x.xxx_hidden_CompanyId != nil {
			return *x.xxx_hidden_CompanyId
		}
		return ""
	}
	return ""
}

func (x *CheckinWithCompanyRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CheckinWithCompanyRequest) SetCompanyId(v string) {
	x.xxx_hidden_CompanyId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CheckinWithCompanyRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CheckinWithCompanyRequest) HasCompanyId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CheckinWithCompanyRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *CheckinWithCompanyRequest) ClearCompanyId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CompanyId = nil
}

type CheckinWithCompanyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// token from the QR code
	Token     *string
	CompanyId *string
}

func (b0 CheckinWithCompanyRequest_builder) Build() *CheckinWithCompanyRequest {
	m0 := &CheckinWithCompanyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.CompanyId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_CompanyId = b.CompanyId
	}
	return m0
}

type CheckinWithCompanyResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User *identity.User         `protobuf:"bytes,1,opt,name=user"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckinWithCompanyResponse) Reset() {
	*x = CheckinWithCompanyResponse{}
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinWithCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinWithCompanyResponse) ProtoMessage() {}

func (x *CheckinWithCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CheckinWithCompanyResponse) GetUser() *identity.User {
	if x != nil {
		return x.xxx_hidden_User
	}
	return nil
}

func (x *CheckinWithCompanyResponse) SetUser(v *identity.User) {
	x.xxx_hidden_User = v
}

func (x *CheckinWithCompanyResponse) HasUser() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_User != nil
}

func (x *CheckinWithCompanyResponse) ClearUser() {
	x.xxx_hidden_User = nil
}

type CheckinWithCompanyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User *identity.User
}

func (b0 CheckinWithCompanyResponse_builder) Build() *CheckinWithCompanyResponse {
	m0 := &CheckinWithCompanyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	return m0
}

var File_hestia_jobfair_checkin_v1_checkin_proto protoreflect.FileDescriptor

var file_hestia_jobfair_checkin_v1_checkin_proto_rawDesc = string([]byte{
	0x0a, 0x27, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2f, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72,
	0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x68, 0x65, 0x73, 0x74, 0x69,
	0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x34, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2f,
	0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2f, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a,
	0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x68, 0x65, 0x73, 0x74, 0x69,
	0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x50, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x64, 0x22, 0x52, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0xf6, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x07, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x12, 0x29, 0x2e, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2e, 0x6a, 0x6f,
	0x62, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72,
	0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x12,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x12, 0x34, 0x2e, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66,
	0x61, 0x69, 0x72, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x68, 0x65, 0x73, 0x74, 0x69,
	0x61, 0x2e, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69, 0x72, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x27, 0x5a, 0x1d, 0x68, 0x65, 0x73, 0x74, 0x69, 0x61, 0x2f, 0x6a, 0x6f, 0x62, 0x66, 0x61, 0x69,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x92, 0x03, 0x05, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hestia_jobfair_checkin_v1_checkin_proto_goTypes = []any{
	(*CheckinRequest)(nil),             // 0: hestia.jobfair.checkin.v1.CheckinRequest
	(*CheckinResponse)(nil),            // 1: hestia.jobfair.checkin.v1.CheckinResponse
	(*CheckinWithCompanyRequest)(nil),  // 2: hestia.jobfair.checkin.v1.CheckinWithCompanyRequest
	(*CheckinWithCompanyResponse)(nil), // 3: hestia.jobfair.checkin.v1.CheckinWithCompanyResponse
	(*identity.User)(nil),              // 4: hestia.jobfair.identity.v1.User
}
var file_hestia_jobfair_checkin_v1_checkin_proto_depIdxs = []int32{
	4, // 0: hestia.jobfair.checkin.v1.CheckinResponse.user:type_name -> hestia.jobfair.identity.v1.User
	4, // 1: hestia.jobfair.checkin.v1.CheckinWithCompanyResponse.user:type_name -> hestia.jobfair.identity.v1.User
	0, // 2: hestia.jobfair.checkin.v1.CheckinService.Checkin:input_type -> hestia.jobfair.checkin.v1.CheckinRequest
	2, // 3: hestia.jobfair.checkin.v1.CheckinService.CheckinWithCompany:input_type -> hestia.jobfair.checkin.v1.CheckinWithCompanyRequest
	1, // 4: hestia.jobfair.checkin.v1.CheckinService.Checkin:output_type -> hestia.jobfair.checkin.v1.CheckinResponse
	3, // 5: hestia.jobfair.checkin.v1.CheckinService.CheckinWithCompany:output_type -> hestia.jobfair.checkin.v1.CheckinWithCompanyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hestia_jobfair_checkin_v1_checkin_proto_init() }
func file_hestia_jobfair_checkin_v1_checkin_proto_init() {
	if File_hestia_jobfair_checkin_v1_checkin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hestia_jobfair_checkin_v1_checkin_proto_rawDesc), len(file_hestia_jobfair_checkin_v1_checkin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hestia_jobfair_checkin_v1_checkin_proto_goTypes,
		DependencyIndexes: file_hestia_jobfair_checkin_v1_checkin_proto_depIdxs,
		MessageInfos:      file_hestia_jobfair_checkin_v1_checkin_proto_msgTypes,
	}.Build()
	File_hestia_jobfair_checkin_v1_checkin_proto = out.File
	file_hestia_jobfair_checkin_v1_checkin_proto_goTypes = nil
	file_hestia_jobfair_checkin_v1_checkin_proto_depIdxs = nil
}
